-- ■itemsテーブル
create table items (
  id bigint generated by default as identity,
  name text,
  category text,
  type int,
  checked boolean default false,
  last_price int,
  last_purchased_date date,
  note text
);

-- ■purchase_history
create table purchase_history (
  id bigint generated by default as identity,
  item_id bigint,
  price int,
  note text,
  purchased_date date
);